services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: frontend
    expose:
      - "9000"

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: backend
    expose:
      - "5252"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend